services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    container_name: practica7-cicd-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
