FROM node:20-bookworm-slim

LABEL maintainer="practica7-cicd"

ENV NODE_ENV=production
ENV PORT=3000

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --omit=dev

COPY src ./src

VOLUME ["/usr/src/app/logs"]

EXPOSE 3000

CMD ["npm", "start"]
